Replace Scrutinizer with Codecov
facile-it/facile-coding-standard pull request #31
Opened 2021-01-18 20:46 UTC by Jean85

2021-01-19 09:32 UTC, thomasvargiu requested changes

2021-01-19 09:32 UTC, thomasvargiu commented on .github/workflows/continuous-integration.yml
> -        if: "${{ matrix.coverage == 'true' }}"
Should we run the coverage for every stage? There is a reason?
IMHO is not necessary and it increase the running time git GH.

2021-01-19 16:11 UTC, Jean85 commented on .github/workflows/continuous-integration.yml
> -        if: "${{ matrix.coverage == 'true' }}"
The running time difference is negligible on such a small test suite, also thanks to pcov. But if you prefer it, I'll restore that part.

2021-01-20 14:55 UTC, thomasvargiu approved these changes

2021-01-25 08:25 UTC, merged